[project]
name = "open-ehr-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=2.16.1",
    "pydantic>=2.11.4",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.40",
]
